apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eks-nginx
  name: eks-nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: eks-nginx
  template:
    metadata:
      labels:
        app: eks-nginx
    spec:
      containers:
      - image: 230308419214.dkr.ecr.ap-northeast-2.amazonaws.com/ecr_nginx:88c602f
        name: eks-nginx























